"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n  \
[󱞪](fg:magenta) \
"""

# format = '$all'

palette = "0x000000"

[palettes.0x000000]
black   = '#282420'
red     = '#f3ac6f'
yellow  = '#f3ac6f'
green   = '#f3ac6f'
blue    = '#f3ac6f'
cyan    = '#f3ac6f'
magenta = '#f3ac6f'

[directory]
format = "(fg:black)[ $path ]($style)(fg:black) "
style = "bg:black fg:blue"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Audio = " "
Pictures = " "

[fill]
style = "fg:black"
symbol = " "

[git_branch]
format = "(fg:black)[ $symbol $branch ]($style)(fg:black) "
style = "bg:black fg:cyan"
symbol = ""

[git_status]
disabled = false
style = "bg:black fg:red"
format = '(fg:black)([$all_status$ahead_behind]($style))(fg:black) '
up_to_date = '[ ✓ ](bg:black fg:magenta)'
untracked = '[?\($count\)](bg:black fg:yellow)'
stashed = '[\$](bg:black fg:magenta)'
modified = '[!\($count\)](bg:black fg:yellow)'
renamed = '[»\($count\)](bg:black fg:magenta)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:black fg:yellow)'
ahead = '[⇡\(${count}\)](bg:black fg:cyan)'
diverged = '⇕[\[](bg:black fg:magenta)[⇡\(${ahead_count}\)](bg:black fg:cyan)[⇣\(${behind_count}\)](bg:black fg:green)[\]](bg:black fg:iris)'
behind = '[⇣\(${count}\)](bg:black fg:green)'

[time]
disabled = true
format = " (fg:black)[ $time 󰴈 ]($style)(fg:black)"
style = "bg:black fg:green"
time_format = "%H:%M"
use_12hr = true

[username]
disabled = false
format = "(fg:black)[ 󰧱 $user ]($style)(fg:black) "
show_always = true
style_root = "bg:black fg:magenta"
style_user = "bg:black fg:magenta"

# Languages

[c]
style = "bg:black fg:blue"
format = " (fg:black)[ $symbol$version ]($style)(fg:black)"
disabled = false
symbol = " "

[elixir]
style = "bg:black fg:blue"
format = " (fg:black)[ $symbol$version ]($style)(fg:black)"
disabled = false
symbol = " "

[elm]
style = "bg:black fg:blue"
format = " (fg:black)[ $symbol$version ]($style)(fg:black)"
disabled = false
symbol = " "

[golang]
style = "bg:black fg:blue"
format = " (fg:black)[ $symbol$version ]($style)(fg:black)"
disabled = false
symbol = " "

[haskell]
style = "bg:black fg:blue"
format = " (fg:black)[ $symbol$version ]($style)(fg:black)"
disabled = false
symbol = " "

[java]
style = "bg:black fg:blue"
format = " (fg:black)[ $symbol$version ]($style)(fg:black)"
disabled = false
symbol = " "

[julia]
style = "bg:black fg:blue"
format = " (fg:black)[ $symbol$version ]($style)(fg:black)"
disabled = false
symbol = " "

[nodejs]
style = "bg:black fg:blue"
format = " (fg:black)[ $symbol$version ]($style)(fg:black)"
disabled = false
symbol = "󰎙 "

[nim]
style = "bg:black fg:blue"
format = " (fg:black)[ $symbol$version ]($style)(fg:black)"
disabled = false
symbol = "󰆥 "

[rust]
style = "bg:black fg:blue"
format = " (fg:black)[ $symbol$version ]($style)(fg:black)"
disabled = false
symbol = " "

[scala]
style = "bg:black fg:blue"
format = " (fg:black)[ $symbol$version ]($style)(fg:black)"
disabled = false
symbol = " "

[python]
style = "bg:black fg:blue"
format = " (fg:black)[ $symbol$version ]($style)(fg:black)"
disabled = false
symbol = " "

[conda]
style = "bg:black fg:blue"
format = " (fg:black)[ $symbol$environment ]($style)(fg:black)"
disabled = false
symbol = " "

