# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
foreground        = "#eeeeee"
background        = "#000000"
dim_foreground    = "#888888"
bright_foreground = "#ffffff"

[colors.cursor]
text   = "#eeeeee"
cursor = "#ff0000"

[colors.vi_mode_cursor]
text =   "#000000"
cursor = "#888888"

[colors.search.matches]
foreground = "#888888"
background = "#000000"

[colors.search.focused_match]
foreground = "#000000"
background = "#ff0000"

[colors.hints.start]
foreground = "#888888"
background = "#000000"

[colors.hints.end]
foreground = "#888888"
background = "#000000"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#eeeeee"
background = "#000000"

[colors.selection]
text = "#eeeeee"
background = "#888888"

[colors.normal]
black   = "#222222"
red     = "#ee0000"
green   = "#00ee00"
yellow  = "#dddddd"
blue    = "#cccccc"
magenta = "#ee00ee"
cyan    = "#00eeee"
white   = "#eeeeee"

[colors.bright]
black   = "#333333"
red     = "#ff0000"
green   = "#00ff00"
yellow  = "#eeeeee"
blue    = "#dddddd"
magenta = "#ff00ff"
cyan    = "#00ffff"
white   = "#ffffff"

[colors.dim]
black   = "#000000"
red     = "#dd0000"
green   = "#00dd00"
yellow  = "#cccccc"
blue    = "#bbbbbb"
magenta = "#dd00dd"
cyan    = "#00dddd"
white   = "#dddddd"
