# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
foreground        = "#D5D4C0"
background        = "#35474B"
dim_foreground    = "#888888"
bright_foreground = "#D5D4C0"

[colors.cursor]
text   = "#444444"
cursor = "#D5D4C0"

[colors.vi_mode_cursor]
text =   "#444444"
cursor = "#BB888C"

[colors.search.matches]
foreground = "#444444"
background = "#BB888C"

[colors.search.focused_match]
foreground = "#444444"
background = "#DD888C"

[colors.hints.start]
foreground = "#74888C"
background = "#444444"

[colors.hints.end]
foreground = "#74888C"
background = "#444444"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#D5D4C0"
background = "#74888C"

[colors.selection]
text = "#444444"
background = "#D5D4C0"

[colors.normal]
black   = "#45575B"
red     = "#BB888C"
green   = "#74888C"
yellow  = "#97A7A5"
blue    = "#AAB8B4"
magenta = "#BDC9C0"
cyan    = "#CFD4C6"
white   = "#D5D4C0"

[colors.bright]
black   = "#333333"
red     = "#CC888C"
green   = "#74888C"
yellow  = "#97A7A5"
blue    = "#AAB8B4"
magenta = "#BDC9C0"
cyan    = "#CFD4C6"
white   = "#D5D4C0"

[colors.dim]
black   = "#45575B"
red     = "#BB888C"
green   = "#74888C"
yellow  = "#97A7A5"
blue    = "#AAB8B4"
magenta = "#BDC9C0"
cyan    = "#CFD4C6"
white   = "#D5D4C0"
