[general]

import = ["~/.config/alacritty/themes/doric-fire.toml"]

[font]
size = 14
normal = { family = "DepartureMono Nerd Font", style = "Regular" }

[window]
# opacity = 0.70
opacity = 1.0
# startup_mode = "Maximized"
startup_mode = "Windowed"
blur = true
padding = { x = 8, y = 8 }

[cursor]
style.blinking = "On"

[keyboard]
bindings = [
   { key = "n", mods = "Control|Shift", action = "SpawnNewInstance" }
]

# TODO: Open filepaths

