[general]

import = ["~/.config/alacritty/themes/rose-pine/dist/rose-pine.toml"]

[font]
size = 16
# normal = { family = "CozetteVector Nerd Font", style = "Regular" }
# normal = { family = "InconsolataGo Nerd Font Mono", style = "Regular" }
# normal = { family = "AdwaitaMono Nerd Font", style = "Regular" }
normal = { family = "ShureTechMono Nerd Font", style = "Regular" }
# normal = { family = "Iosevka Nerd Font Mono", style = "Regular" }

[window]
opacity = 0.70
# startup_mode = "Maximized"
startup_mode = "Windowed"
blur = true
padding = { x = 8, y = 8 }

[colors.cursor]
text = "#191724"
cursor = "#eb6f92"

[colors.vi_mode_cursor]
text = "#191724"
cursor = "#eb6f92"

[colors.search.matches]
foreground = "#191724"
background = "#f6c177"

[colors.hints.start]
foreground = "#1f1d2e"
background = "#eb6f92"

[colors.hints.end]
foreground = "#1f1d2e"
background = "#eb6f92"

[cursor]
style.blinking = "On"

[keyboard]
bindings = [
   { key = "n", mods = "Control|Shift", action = "SpawnNewInstance" }
]

# TODO: Open filepaths

